services:
  account-service:
    image: "shadril238/account-service:s4"
    container_name: account-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  card-service:
    image: "shadril238/card-service:s4"
    container_name: card-service
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  loan-service:
    image: "shadril238/loan-service:s4"
    container_name: loan-service
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"