spring:
    application:
        name: "config-server"
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
#                    search-locations: "classpath:/config"
                    search-locations: "file:///home//bs00545//Desktop//spring-boot-microservices//config"  # Path to the directory where the configuration files are stored
server:
    port: 8071